# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true
after-login-command = []

# Startup borders
# Startup SketchyBar
after-startup-command = [
  'exec-and-forget borders active_color=0xffc6a0f6 inactive_color=0xffb7bdf8 width=4.0 style=round',
  'exec-and-forget sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash', 
    '-c',
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse monitor-lazy-center'

# Layout
# accordion-padding = 30

[gaps]
inner.horizontal = 15
inner.vertical = 15
outer.left = 17
outer.bottom = 15
outer.top = 75
outer.right = 17

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    # Open Ghostty @todo
    # alt-g = '''exec-and-forget osascript -e '
    # tell application "Ghostty"
    #     do script
    #     activate
    # end tell'
    # '''

    # i3 wraps focus by default
    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    alt-c = 'split horizontal'
    alt-v = 'split vertical'
    alt-cmd-h = 'join-with left'
    alt-cmd-l = 'join-with right'
    alt-cmd-j = 'join-with down'
    alt-cmd-k = 'join-with up'

    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    alt-1 = 'workspace Browser'
    alt-2 = 'workspace BrowserWork'
    alt-3 = 'workspace Terminal'
    alt-8 = 'workspace Misc'
    alt-9 = 'workspace Orbstack'
    alt-0 = 'workspace Email'
    alt-p = 'workspace IDE'
    alt-m = 'workspace Terminal'

    alt-shift-1 = 'move-node-to-workspace Browser'
    alt-shift-2 = 'move-node-to-workspace BrowserWork'
    alt-shift-3 = 'move-node-to-workspace Terminal'
    alt-shift-8 = 'move-node-to-workspace Misc'
    alt-shift-9 = 'move-node-to-workspace Orbstack'
    alt-shift-0 = 'move-node-to-workspace Email'
    alt-shift-p = 'move-node-to-workspace IDE'
    alt-shift-m = 'move-node-to-workspace Terminal'

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[[on-window-detected]]
    if.app-id = 'com.mitchellh.ghostty'
    run = 'move-node-to-workspace Terminal'

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = 'move-node-to-workspace Browser'

[[on-window-detected]]
    if.app-id = 'dev.kdrag0n.MacVirt'
    run = 'move-node-to-workspace Orbstack'

[[on-window-detected]]
    if.app-id = 'com.jetbrains.PhpStorm'
    run = 'move-node-to-workspace IDE'

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = 'move-node-to-workspace Misc'

[[on-window-detected]]
    if.app-id = 'com.readdle.smartemail-Mac'
    run = 'move-node-to-workspace Email'

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace Misc'
